### ISSUE TITLE
Not sending embedded messages

### ISSUE THREAD

**Issue by LeonardM01** [nicolasmf/discord.js-poll#7]
Noticed a problem in the index.js file which is responsible for the poll function...with the new version of discord.js and embedded message should and only can be sent like so:
```message.channel.send({embeds: [embed]}); ``` 
unlike before:
```message.channel.send({ embed}) ; ``` 
So if you just implement that the poll function will be usable again.

**Comment by nicolasmf** [comment]
Hey thanks for the tip ! I'll do that right away. It's been a while since I worked on this project, sorry

**Comment by nicolasmf** [comment]
Fixed.

**Comment by AstralRedshift** [comment]
Hey, i'm just for asking if you updated your index.js file into the NPM Package.
Because i'm getting the same issue at line 17.
Thanks so much

**Comment by nicolasmf** [comment]
Hey !
Yes I did. Have you tried updating the package ?

**Comment by AstralRedshift** [comment]
> Hey ! Yes I did. Have you tried updating the package ?

Yes, same problem, version 1.1.2
I did, "npm uninstall discord.js-poll" and "npm install discord.js-poll", from 1.1.2 to 1.1.2

**Comment by nicolasmf** [comment]
Fixed in version 1.2.1. Thanks !
